title: Your little secret VendingDroid
author: 
description: > # this means to ignore newlines until "baseurl:"
  货品掉落中...

# social links


show_excerpts: false # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
