title: Your awesome little————
author: MO型自动贩售机器人
lofter: 丘涂
description: > # this means to ignore newlines until "baseurl:"
  载入中...

# social links
popiask: popiask.cn/RVNogG # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
